baseURL = 'https://example.com/'
languageCode = 'en-us'
title = 'Startpage'
theme = "hugo-static-startpage"

[Params]
  siteName = 'Hugo Static Startpage'
  author = 'Guillaume Le Roy'
  github = "https://github.com/atlza"